//! Build script for edge-driver.
//!
//! Walks the `std/` directory at compile time and generates a Rust source file
//! that embeds every `.edge` standard library file as a static string.  The
//! generated file is included into the crate via `include!` and exposes:
//!
//! ```rust,ignore
//! pub static STD_SOURCES: &[(&str, &str)];
//! ```
//!
//! where each entry is `("module/key", "<source text>")`.  The module key is
//! the file path relative to `std/`, with the `.edge` extension removed and
//! path separators normalised to `/`.  For example:
//!
//! - `std/math.edge`              → key `"math"`
//! - `std/tokens/erc20.edge`     → key `"tokens/erc20"`
//! - `std/math/signed_wad.edge`  → key `"math/signed_wad"`

use std::{fs, path::Path};

fn main() {
    // Locate std/ relative to this crate's manifest directory.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let std_dir = Path::new(&manifest_dir).join("../../std");

    // Tell Cargo to re-run this script whenever any std/ file changes.
    println!("cargo:rerun-if-changed=../../std");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("std_embedded.rs");

    if !std_dir.is_dir() {
        // std/ doesn't exist at build time (e.g. a downstream consumer of the
        // crate that didn't check out the full workspace).  Emit an empty table
        // so the crate still compiles; imports will only work if the user
        // provides --std-path / EDGE_STD_PATH at runtime.
        fs::write(
            &out_path,
            "pub static STD_SOURCES: &[(&str, &str)] = &[];\n",
        )
        .expect("failed to write std_embedded.rs");
        return;
    }

    let mut entries: Vec<(String, String)> = Vec::new();
    collect_entries(&std_dir, &std_dir, &mut entries);

    // Sort for deterministic output.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from(
        "/// Embedded edge standard library sources, generated by build.rs.\n\
         /// Each entry is (module_key, source) where module_key is the file\n\
         /// path relative to std/ with the .edge suffix removed.\n\
         pub(crate) static STD_SOURCES: &[(&str, &str)] = &[\n",
    );

    for (key, source) in &entries {
        // Use Debug formatting to produce a quoted, escaped Rust string literal.
        code.push_str(&format!("    ({key:?}, {source:?}),\n"));
    }

    code.push_str("];\n");

    fs::write(&out_path, code).expect("failed to write std_embedded.rs");
}

fn collect_entries(base: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    let read_dir = match fs::read_dir(dir) {
        Ok(rd) => rd,
        Err(_) => return,
    };

    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_entries(base, &path, entries);
        } else if path.extension().and_then(|e| e.to_str()) == Some("edge") {
            let rel = path
                .strip_prefix(base)
                .expect("path not under std/")
                .to_str()
                .expect("non-UTF-8 path in std/")
                .replace('\\', "/"); // normalise Windows separators

            let key = rel
                .strip_suffix(".edge")
                .expect("already checked extension")
                .to_string();

            let source =
                fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {path:?}: {e}"));

            entries.push((key, source));
        }
    }
}
