//! Edge Language Compiler Driver
#![warn(missing_docs)]
#![deny(unused_must_use, rust_2018_idioms)]

pub mod compiler;
pub mod config;
pub mod session;

/// Embedded standard library sources, generated by build.rs.
/// Maps module key (e.g. `"tokens/erc20"`) to `.edge` source text.
mod std_embedded {
    include!(concat!(env!("OUT_DIR"), "/std_embedded.rs"));
}
