name: Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9am UTC

jobs:
  security_audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          tools: cargo-deny
          rust-cache-shared-key: "stable"
      - run: cargo deny check advisories
