name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          rust-cache-shared-key: "stable"
          rust-cache-save: ${{ github.ref == 'refs/heads/main' }}
      - run: just build-ci

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          tools: cargo-nextest
          rust-cache-shared-key: "stable"
      - run: just test-ci

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          toolchain: nightly
          components: rustfmt
          rust-cache-shared-key: "nightly"
          rust-cache-save: ${{ github.ref == 'refs/heads/main' }}
      - run: just check-format

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          components: clippy
          rust-cache-shared-key: "stable"
      - run: just check-clippy-ci

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          tools: cargo-deny
          rust-cache-shared-key: "stable"
      - run: just check-deny

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          rust-cache-shared-key: "stable"
      - run: just check-docs
